### ISSUE TITLE
Rsync issue on Windows

### ISSUE THREAD

**Issue by nevf** [pstadler/flightplan#1]
Hi, I'm trying to set up and use Flightplan on Windows (8) and am having a problem with the command line fly passes to rsync. The double quotes around the filename are the issue.

`$(echo "browser/main-built.js") | rsync --files-from - -azv --rsh="ssh" ./ some_host`

`local > building file list ... local > rsync: link_stat "/cygdrive/c/webapps/clibu/"browser/main-built.js" " failed: No such file or directory (2)
done`

If I run this directly from the command line without the doubles quotes it works.
`(echo browser/main-built.js) | rsync --files-from - -azv --rsh="ssh" ./`

I am using Rsync that comes with cwRsync.

I've tried: `filesToCopy = ["browser/main-built.js"]` and `filesToCopy = "browser/main-built.js"`

Flightplan looks really good and is something I've been wanting for a while now.

-Neville

**Comment by PCMRStudio** [comment]
this is still not resolved, why is it closed?

**Comment by nevf** [comment]
@PCMRStudio FYI I gave up on FlightPlan long ago and moved to shipit and have subsequently moved to  gulp and https://www.npmjs.com/package/rsync-slim which works a treat.

**Comment by pstadler** [comment]
@PCMRStudio what's your problem?
@nevf you're not helping much.

**Comment by PCMRStudio** [comment]
```
$ fly --debug production
✈ Running default:production
✈ Executing local task
localhost $ cd bundle/ && git ls-files
localhost ● ok
localhost $ rsync --files-from b3c199abeaf11490d9daed8cc80bab1a -azvv --rsh="ssh -p22" ./ web@server:/tmp/deploy-1458570451736
localhost > opening connection using: ssh -p22 -l web server rsync --server -vvlogDtpRze.LsfxC . /tmp/deploy-1458570451736  (10 args)
localhost > dup() in/out/err failed
localhost > rsync: connection unexpectedly closed (0 bytes received so far) [sender]
localhost > rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
localhost ● failed (12)
● Command exited abnormally on localhost

```

**Comment by bfday** [comment]
Still no solution. So sad. My problem is using custom port and sertificates. So i should write something like this:
`rsync -avz --rsh='ssh -p 9999 -i ~/.ssh/id_rsa' name@name.domain.com:/var/www/blahblablah.sql tmp/blahblah.sql`

without 
`--rsh='ssh -p 9999 -i ~/.ssh/id_rsa'` 
parameter it's works perfectly, but with this parameter i have an issue described above.

my console says:
```
dup() in/out/err failed
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [Receive
r=3.1.2]
```

**Comment by pstadler** [comment]
Maybe you want to simply execute the command on your own then?

**Comment by hardikvjoshi** [comment]
Same issue as bfday...and looks like it is not going to be fixed.... :-)

**Comment by pstadler** [comment]
I can only guess, but the comments in this thread may solve your problems:
https://github.com/mitchellh/vagrant/issues/6677#issuecomment-247069831

Please let me know

**Comment by manjeshpv** [comment]
https://www.itefix.net/content/cwrsync-free-edition this link worked for me
