### ISSUE TITLE
Rsync with unicode filenames

### ISSUE THREAD

**Issue by Znarkus** [pstadler/flightplan#102]
With unicode filenames, the path is returned as `"path/to/file\302.md"` instead of `path/to/file.md`. Note the `"`.

This creates this rsync problem:

```
localhost > rsync: link_stat "/some/path/"path/to/file\302.md"" failed: No such file or directory (2)
```

Checked the tmpFile that is created by `Shell.prototype.transfer` and `"` are present on lines with unicode paths.

```
$ fly --version
0.6.4
$ rsync --version
rsync  version 2.6.9  protocol version 29
```

**Comment by pstadler** [comment]
The question is if this is a bug in rsync itself. Please provide some context, how you pass this file to rsync.

**Comment by Znarkus** [comment]
This is the command that is executed:

```
https://github.com/pstadler/flightplan/blob/627feccc7680cecf12b512513acbc0d12ca14f3c/lib/transport/shell.js#L110
```

**Comment by pstadler** [comment]
That's not really helpful. I need to know what you're passing with the `files` parameter.

**Comment by pstadler** [comment]
Is this still a problem? If so, please provide further information.
