### ISSUE TITLE
Transfer from Remote

### ISSUE THREAD

**Issue by pleribus** [pstadler/flightplan#103]
I'm reviewing flightplan for a particular use case, but unsure if this can be done:

We have a staging server with CMS which content managers enter content into for review, including text images and video - content isn't source controlled (due to size).

Looking for a way to deploy CMS templates (via git repo) and content via file transfer + ssh commands

So ideally would need to do following:

Templates:
local -> staging
local -> live

Content: 
staging -> live 
(or staging -> local -> live)

I just can't figure a way to get the content files down from the staging server to transfer to live based on docs I've read (though may have missed it)

Any help appreciated.

**Comment by pstadler** [comment]
How about using scp for downloading a tarfile or something like that? Please let me know if you have any further questions.
