### ISSUE TITLE
After gulp installation: Failed abnormally

### ISSUE THREAD

**Issue by lightningboss** [pstadler/flightplan#105]
I've installed gulp and defined some tasks. I also installed a lot of node-modules for gulp.

The following happened: flightplan gives me an error if I do my "fly production" command (that worked before!)
```
fly production
✈ Running default:production
✈ Executing local task
localhost Copy files to remote hosts
localhost $ git ls-files
localhost × failed (null)
× Command exited abnormally on localhost
```

After checking out another commit, where gulp is not installed, everything works fine.

Any ideas, why this is happening?

**Comment by pstadler** [comment]
It seems like there are too many files listed. Try to increase the maxBuffer setting for this specific cimmand, as described in the readme:

```javascript
// increase maxBuffer for child_process#exec()
local.ls('-al', {exec: {maxBuffer: 2000*1024}});
```
Use a greater value if this is not working

**Comment by peterborghard** [comment]
@pstadler is there a way to disable maxBuffer?  I need to keep increasing this value every few months.  Also, is the buffer related to the actual file size?  Or the file count?

**Comment by pstadler** [comment]
It's the number of characters that can be received by `child_process#exec`. Try `maxBuffer: Infinity`.

**Comment by peterborghard** [comment]
That worked, thanks @pstadler !
