### ISSUE TITLE
inherit EventEmitter

### ISSUE THREAD

**Issue by evilebottnawi** [pstadler/flightplan#106]
Also emit event start, stop, local, remote, target and maybe another. That do you think

**Comment by pstadler** [comment]
What's the goal?

**Comment by evilebottnawi** [comment]
@pstadler i use own build system based on promises and parallels, inside build system i use flightplan. I need start and end (etc) event for my own solution.

**Comment by pstadler** [comment]
You can do this on your own, no need for flightplan to emit these events directly.

Related: https://github.com/pstadler/flightplan/issues/74

**Comment by evilebottnawi** [comment]
@pstadler i use directly run, but i don't know when flightplan is finished.

**Comment by evilebottnawi** [comment]
@pstadler after flightplan is finished i need push message to developer
