### ISSUE TITLE
auto escape string in exec and other task

### ISSUE THREAD

**Issue by evilebottnawi** [pstadler/flightplan#108]
RegExp for escaping https://github.com/xxorax/node-shell-escape

**Comment by evilebottnawi** [comment]
@pstadler why? if i you this code, i get error.
```javascript
remote.exec('mysql -uroot -proot -e "SELECT * FROM `table`"');
```
Error throw by reason of use "`"

**Comment by pstadler** [comment]
I don't get it. Just escape your commands as if you would run them manually.

**Comment by evilebottnawi** [comment]
@pstadler may be add option to auto escaping command. I do not propose to use this module, just gave an example.
