### ISSUE TITLE
Remove old files

### ISSUE THREAD

**Issue by Koded** [pstadler/flightplan#109]
As far as I can tell, due to the way Flightplan is using Rsync, old files will not be removed from the server.

I.e., if I deploy some files to a server, then remove some files locally, and re-deploy, the files that have been deleted locally will remain on the server.

This is because of a couple of reasons, firstly that the Rsync flag `--delete` isn't being used.  But more importantly, and fundamentally, even if it was it wouldn't remove them because `--from-file` is being used, which means Rsync will ignore delete files.

I'm not sure that Flightplan claims to sync files, just to upload them, so this feels more like an enhancement.

Solving this ticket would help sort this issue out: https://github.com/pstadler/flightplan/issues/71

**Comment by pstadler** [comment]
The idea is indeed not to sync. However, I do understand the need of making transport more flexible. :+1:

**Comment by pstadler** [comment]
I'm closing this in favor of #71

**Comment by Koded** [comment]
Makes sense.  Thanks for confirming @pstadler.
