### ISSUE TITLE
Is it possible to pass command line arguments to flightplan.js?

### ISSUE THREAD

**Issue by haimich** [pstadler/flightplan#112]
First of all let me say that you did an awesome job with flightplan! I used python's Fabric before and also tried Ansible on my project but neither of those solutions made it simple to execute local commands first.

What I'm trying to achieve is this: `fly deploy:dev 0.1.2`

Is it supported by flightplan to read in parameters from the command line?

**Comment by pstadler** [comment]
Glad to hear that.

This is indeed possible:

```bash
# plan.local(function(local) {
#   console.log(plan.runtime.options.argv.remain);
# });

$ fly task:target 0.1.2
# [ 'task:target', '0.1.2' ]
```
