### ISSUE TITLE
Ecmascript 6/7 & Babel support

### ISSUE THREAD

**Issue by devlato** [pstadler/flightplan#114]
Hi! 
Will flightplan have any support of ES6/Babel? Or is it possible to run flightplan programmatically?

**Comment by pstadler** [comment]
Flightplan supports ES6. You can even pass flags known to v8 such as `--harmony`:
```bash
$ fly test --harmony
```

Alternatively you should be able to simply call the file `flightplan.babel.js`. This should automatically require babel if available.

Please let me know how this is working out for you.

**Comment by devlato** [comment]
Yes, it works, thank you
