### ISSUE TITLE
Issue handling privateKey path with space in folder name

### ISSUE THREAD

**Issue by renarsvilnis** [pstadler/flightplan#119]
Hi, having trouble using `privateKey` path for target where the somewhere along the path the folder has a space in its name. Example `Some Folder`.

```javascript
plan.target('production', [{
    host: 'x.x.x.x',
    username: 'deploy',
    agent: process.env.SSH_AUTH_SOCK,
    privateKey: '/path/to/Some Folder/key.pem' 
}]);
```
But when executing plan the path isn't escaped with qoutes it breaks the path into 2 arguments:  `/path/to/Some` and `Folder/key.pem`.

```bash
rsync --files-from /var/folders/2d/xlk3q/T/f537 -az --rsh="ssh -p22 -i /path/to/Some Folder/key.pem ./ deploy@x.x.x.x:/tmp/project
```

Have tried using `privatekey` path that escapes spaces with `\ ` such as shown below, but it gets taken out and it does the same as without using `\ `.

```javascript
plan.target('production', [{
    // ...
    privateKey: '/path/to/Some\ Folder/key.pem' 
}]);
```
Having spaces in folder names isn't a good idea anyway._

**Comment by pstadler** [comment]
This should probably get fixed at some point. Meanwhile you could try to
escape the space in the string using two backslashes: ` \\`

**Comment by renarsvilnis** [comment]
That doubleslash doesn't seem to work either.

**Comment by pstadler** [comment]
This is a bit a wild guess and definitely an ugly solution, but could be suitable as a workaround: `privateKey: '"/path/to/Some Folder/key.pem"' `

**Comment by pstadler** [comment]
Please reopen if this is still a problem.
