### ISSUE TITLE
No work to be done for task "undefined"

### ISSUE THREAD

**Issue by ryanhovland** [pstadler/flightplan#120]
After a updating to the latest version of npm, flightplans that previously worked no longer do. Trying to fly dev or other targets results in this error:

`No work to be done for task "undefined"`

I've tried uninstalling and re-stalling to no avail. Has anyone seen this before? 

p.s. flightplan rocks! Thanks for making it.

**Comment by pstadler** [comment]
could you tell me your exact node and npm versions?

`node -v; npm -v`

If you changed node versions recently, make sure to reinstall flightplan both locally and globally.

**Comment by ryanhovland** [comment]
node: 4.2.6
npm: 3.7.3

I've uninstalled/reinstalled both locally and globally and it didn't fix the issue. Thanks for looking into this.

**Comment by pstadler** [comment]
I don't have any problems running flightplan:

```bash
$ fly task:target
✈ Running task:target
✈ Executing local task
localhost $ node -v; npm -v
localhost > v4.2.6
localhost > 3.7.5
localhost ● ok
✈ Local task finished after 222 ms
✈ Flightplan finished after 223 ms
```

**Comment by pstadler** [comment]
To verify this claim I finally added Node 4.x and 5.x to the test platforms. Builds are all passing: https://github.com/pstadler/flightplan/pull/121

**Comment by ryanhovland** [comment]
More info...

I used to be able to run "fly prod" to execute a flightplan. That's currently returning: No work to be done for task "undefined"

However, I just got it to work properly with "fly default:prod"

I'm not sure why the previous method stopped working for me, but I'm back in action here again. Thanks for looking into this.

**Comment by pstadler** [comment]
I can't reproduce this
