### ISSUE TITLE
Problems to create remote folder

### ISSUE THREAD

**Issue by marcioamr** [pstadler/flightplan#123]
I'm having problems to create a remote folder. It's a simple operation but I can't see the error neither works.

```
plan.remote(function(remote) {
   remote.sudo('mkdir -p /usr/local/tmp_test', {user: 'deploy'});
});
```

**Comment by pstadler** [comment]
I guess user `deploy` doesn't have permission to create directories within `/usr/local`.

**Comment by marcioamr** [comment]
But the console shows "OK". Where can I view the remote ouput?

**Comment by pstadler** [comment]
You're right, there's a problem with escaping sudo commands.

**Comment by pstadler** [comment]
Thanks for the report. Please update to 0.6.10 and let me know how things are going.

Release notes: https://github.com/pstadler/flightplan/releases/tag/0.6.10

**Comment by nikolay** [comment]
This actually broke my stuff. As a command that used to work before, for example, `a b c`, is not escaped to `a\ b\ c`, and Bash says that it can't find `a b c` command, i.e.

```
$ fly xxx:yyy
✈ Running xxx:yyy
✈ Running dynamic hosts configuration
✈ Connecting to '1.2.3.4'
✈ Executing remote task on 1.2.3.4
10.117.4.133 $ sudo -u root -i bash -c 'a\ b\ c'
10.117.4.133 > stdin: is not a tty
10.117.4.133 > bash: a b c: command not found
10.117.4.133 ● failed (127)
● Command exited abnormally on 1.2.3.4
```

**Comment by nikolay** [comment]
@pstadler Without any change in my environment or `flightplan.js`, the above used to work on v0.6.9.

**Comment by marcioamr** [comment]
I was using 0.6.10 version.

On Thu, Mar 3, 2016 at 1:06 PM, Patrick Stadler <notifications@github.com>
wrote:

> Thanks for the report. Please update to 0.6.10 and let me know how things
> are going.
>
> Release notes: https://github.com/pstadler/flightplan/releases/tag/0.6.10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pstadler/flightplan/issues/123#issuecomment-191828812>
> .
>



-- 
*Márcio Alexandre*

marcioamr@gmail.com

**Comment by pstadler** [comment]
Thanks for reporting, [0.6.11](https://github.com/pstadler/flightplan/releases/tag/0.6.11) has been released to fix this problem. 

This also means that this issue is still open and needs to be tackled with a different solution.

**Comment by pstadler** [comment]
I got a potential fix ready, but I'd like to get this tested before releasing it.
Could you please try it out by using the following version as a dependency?

```
"devDependencies": { // or "dependencies"
  "flightplan": "git@github.com:pstadler/flightplan.git#sudo-escape-spaces"
}
```

Followed by `npm install`

**Comment by pstadler** [comment]
Pull request: https://github.com/pstadler/flightplan/pull/127

/cc @zmillman please see previous comment

**Comment by pstadler** [comment]
I just released 0.6.12 which contains the mentioned fix. Please try it and reopen this ticket if the problem persists. 

https://github.com/pstadler/flightplan/releases/tag/0.6.12

**Comment by nikolay** [comment]
@pstadler Still not working...

**Comment by nikolay** [comment]
You do now `sudo -u root -i bash -c "'a b c'"`, which is still wrong... You shouldn't escape command along with its parameters!

**Comment by pstadler** [comment]
For the record: https://github.com/pstadler/flightplan/releases/tag/0.6.13

**Comment by nikolay** [comment]
@pstadler Thanks! It works now!
