### ISSUE TITLE
0.6.10 breaks `remote.with "cd"` under sudo

### ISSUE THREAD

**Issue by zmillman** [pstadler/flightplan#125]
#123 introduced a breaking change: Escaping the space before `&&` means that `cd` doesn't get the correct directory name.

```coffee
remote.with 'cd /home/deploy/my-project', =>
  remote.sudo 'git fetch', {user: 'deploy'}
```

creates a command like

```
sudo -u deploy -i bash -c 'cd\ /home/deploy/my-project\ &&\ git\ fetch'
```

which errors out with

```
bash: cd /home/deploy/my-project : No such file or directory
```

^ note the space after `my-project`

**Comment by pstadler** [comment]
Thanks for catching this stupid bug. I reverted the changes introduced with 0.6.10 and released 0.6.11.
