### ISSUE TITLE
Remote change directory

### ISSUE THREAD

**Issue by marcioamr** [pstadler/flightplan#126]
I can't change the remote directory.

```
remote.cd('/usr/local/folder');
```
Or
```
remote.exec(cd '/usr/local/folder');
```

Neither of them worked for me.

* I'm using 0.6.10 version of Flightplan.

**Comment by pstadler** [comment]
You probably want to use `transport#with()`. Docs: https://github.com/pstadler/flightplan#transportwithcommandoptions-options-fn
