### ISSUE TITLE
Use of extra single quotes results in errors copying the files from tmp dir

### ISSUE THREAD

**Issue by chrene** [pstadler/flightplan#128]
$ sudo -u root -i bash -c "'cp -R /tmp/project-1457472418137 ~/'"
> bash: cp -R /tmp/project-1457472418137 ~/: No such file or directory
● failed (127)
● Command exited abnormally on xxxxxxxxxxx

The error arises because "'cp -R /tmp/project-1457472418137 ~/'"
has too many quotes.
Removing the single quotes will solve the problem.

The problem is not there using version 0.6.11

**Comment by nikolay** [comment]
@pstadler @chrene This is the same as #123. Flightplan has been broken for me since this "improvement" got into the picture.

**Comment by pstadler** [comment]
https://github.com/pstadler/flightplan/releases/tag/0.6.13
