### ISSUE TITLE
How to get a list of all files and sub folders under a folder without git list?

### ISSUE THREAD

**Issue by rijine** [pstadler/flightplan#133]
@pstadler 
public /
         styles/
                 extra/some.css
                 admin/someadmin.css
         app.js
How to customize flighplan like gulp/grunt /**/* 
src ['app.js' , 'styles/**/*.js'] ??

**Comment by pstadler** [comment]
You can either use something like [glob](https://github.com/isaacs/node-glob) (which is probably used in grunt too) or use `find` to get a list of files, e.g.:

```sh
var files = local.exec('find node_modules -type f -print0');
```

**Comment by rijine** [comment]
@pstadler Ohh great..thank you
