### ISSUE TITLE
Encrypted private key detected, but no passphrase given

### ISSUE THREAD

**Issue by thierryc** [pstadler/flightplan#137]
I get this error after I upgrade to El Capitan. rsync works fine but remote action is blocked by this error. 

✈ Connecting to 'myWebServer.com'
● Error connecting to 'myWebServer.com': Encrypted private key detected, but no passphrase given

I have passphrase for this key. But fly do asking me to enter it. 

local.transfer -> OK.
plan.remote -> Error.

Than you for your feedback

**Comment by thierryc** [comment]
I try 

```
ssh-add -K path/to/my_key

```

Same issue

**Comment by pstadler** [comment]
After adding your key to the ssh agent, make sure to set `agent: process.env.SSH_AUTH_SOCK`

See here: https://github.com/pstadler/flightplan/issues/55

**Comment by thierryc** [comment]
Yes it is. 

agent: process.env.SSH_AUTH_SOCK,

**Comment by thierryc** [comment]
Did flightplan use .ssh/config file ?

**Comment by pstadler** [comment]
This is not so simple, check out the discussion here: https://github.com/pstadler/flightplan/issues/117

**Comment by thierryc** [comment]
Thank you. 

 The same key on the same serveur works for Rsync ! 

I get this (like) when I add -d to my fly !

opening connection using ssh -p22 -i /Users/xoxo/.ssh/id_rsa -l "user@server.com" server.com rsync --server -vvlogDtpRz . /home/server.com/html

**Comment by thierryc** [comment]
I have found this on SSH doc : 

https://github.com/mscdex/ssh2#client-methods

passphrase - string - For an encrypted private key, this is the passphrase used to decrypt it. Default: (none)

I try this settings ! Same issue. 

Adding passphrase in config file is not a very good option. 



```
staging: {
    host: 'server.com',
    username: 'toto@server.com',
    agent: process.env.SSH_AUTH_SOCK,
    webRoot: '/home/server.com/html',
    sudoUser: 'www',
    privateKey: '/Users/toto/.ssh/id_rsa',
    passphrase: 'zorglube'
 }


```

**Comment by kyrcha** [comment]
@thierryc Thank you for the suggestion as it was exactly what I was looking for. With respect to adding a prompt and then including the passphrase on the fly (instead of a config file), I was wondering if there something more elegant than:

    plan.local('deploy', function(local) {
        var passphrase = local.prompt('Enter your passphrase:', { hidden: true });
        plan.target().runtime.hosts.forEach(function(host) {
            host.passphrase = passphrase;
        });
        local.log('=== Copy files to remote hosts ===');
        var filesToCopy = local.exec('git ls-files', {silent: true});
        // rsync files to all the destination's hosts
        local.transfer(filesToCopy, '/tmp/' + tmpDir);
    });

**Comment by thierryc** [comment]
Great ! Thank you @kyrcha

**Comment by fahric** [comment]
I started getting this problem after i updated my mac to use Sierra. Not sure what has changed. Great solution. Thank you @thierryc and @kyrcha

**Comment by pstadler** [comment]
This is indeed problem since Sierra. Try adding this to ~/.ssh/config:

```
Host *
  UseKeychain yes
  AddKeysToAgent yes
```
