### ISSUE TITLE
Suppress printing command

### ISSUE THREAD

**Issue by ravi** [pstadler/flightplan#138]
Currently there are options to `exec` to suppress output, ignore failure, etc (others?). I do not see an option or mechanism to suppress printing of the command itself. I have a case where I supply a password to a command, and I would like to avoid having the password logged.

**Comment by pstadler** [comment]
Makes somehow sense to me, but then again, you could simply source a file which exports an env variable or something like that.

**Comment by ravi** [comment]
True, I could do:
```
local.exec("mysql ... -p`some-command` ....");
```
Where `some-command` returns the password.

**Comment by pstadler** [comment]
Exactly, or even better:

```js
local.exec('source .secrets; mysql -p $MYSQL_PASSWORD ...');

// .secrets
MYSQL_PASSWORD=mypassword
```

**Comment by ravi** [comment]
Okay... unless you feel this may be a generally useful feature, please feel free to close. Thank you.
