### ISSUE TITLE
Bunch output by host

### ISSUE THREAD

**Issue by ravi** [pstadler/flightplan#139]
Currently the output from Flightplan is printed as and when things happen, making it difficult to know what happened per host. It would be nice if there were an option to bunch output by host. Perhaps too much work and may not be a universal need, so please consider it low priority, if at all.

**Comment by pstadler** [comment]
All the lines prefixed with the host already and it makes sense to see what's happening in real time.
Simply pipe the output into a file and tail / grep the host you're interested in.
