### ISSUE TITLE
Consider removing C++ dependency

### ISSUE THREAD

**Issue by danielgtaylor** [pstadler/flightplan#14]
Right now Flightplan depends on the `fibers` module. Unfortunately the module is written in C++ and [requires a C++ compiler](https://github.com/laverdet/node-fibers#other-notes) to be set up for installation, which is inconvenient. While I personally don't mind, it makes onboarding new developers more difficult.

I don't have much experience with coroutines and promises but maybe another library could be used?

**Comment by renarsvilnis** [comment]
I'm resurrecting this.

Not that familiar with fibers, but can't it just be dropped in favour of async-await?

My use case right now, I need to do some async stuff in the local, but it fails `Error: Can't wait without a fiber`. I'm ready to contribute the changes if needed.

```javascript
plan.local(async (local) => {
  // ... other stuff

  async function addItems (items) {
    const promises = items.map(async (fileOrFolder) => {
      if (isGlob(fileOrFolder)) {
        const sublist = await globP(fileOrFolder);
        await addItems(sublist);
      } else {
        filesToCopy.add(fileOrFolder);
      }
    });

    if (promises.length) {
      await Promise.all(promises);
    }
  }

  local.log('Building client files');
  local.exec('npm run build:prod', {silent: true});

  local.log('Fetching build result client file list');
  await addItems(fileWhiteList);

  local.log('Copy files to remote hosts');
  local.transfer([...filesToCopy], `/tmp/${tmpDir}`);
});
```

**Comment by pstadler** [comment]
See: https://github.com/pstadler/flightplan/issues/162

**Comment by pstadler** [comment]
@renarsvilnis Sorry, somehow the following sentence got lost:
If you're willing to perform such a huge refactoring and hopefully continue to maintain this project in the future, I will happily add you as a contributor.
