### ISSUE TITLE
Change the root (working directory) used in the transfer method

### ISSUE THREAD

**Issue by faressoft** [pstadler/flightplan#142]
Is there any way to change the local root directory that the transfer tries to find the files in it because my files is placed in a sub-directory.

```
.
├── Gruntfile.js
├── dist
├── flightplan.js
└── src
```

I need to upload the contents of the dist directory.

**Comment by pstadler** [comment]
Just use something like 

```js
var files = local.exec('find ./dist -type f -print0', { silent: true });
local.transfer(files, '/tmp/flightplan');

**Comment by ronalson** [comment]
Sorry for opening up this question again, but I think the issue I'm facing right now is pretty close to this one. 

I'm trying to `transfer()` the content of a dist/ folder to a specific directory in the server. However, I could not make `var filesToCopy` point to the content whitin dist/. Everything I've tried so far ends up pushing the whole directory (dist/).

Following your answer, I searched for a shell parameter that would give me only the paths within the /dist but I could not make it work. The closest I got was this:

```
find ./dist -type f -exec basename {} \;
```

which return only files names w/o the sub-directory structure. I'm pretty new into this and shell scripting is certainly something I'm not used to.

Hope you can give me a hint.

**Comment by pstadler** [comment]
As far as I know the only way to accomplish this with `find` is to `cd` into the folder first. e.g. `local.exec('cd ./dist; find . -type f')`. You could also use [`with`](https://github.com/pstadler/flightplan#transportwithcommandoptions-options-fn) if that's more convenient for you.

**Comment by ronalson** [comment]
thanks for the quick answer, @pstadler. 

Indeed the `local.exec('cd ./dist; find . -type f')` outputed the content within the /dist folder, however it didn't work as I expected. Maybe I should give you more details about what I'm trying to do:

I develop my project using gulp and it has the following folder structure:

```
myProject
   | /dev
   |__ /css
   |__ /js
   |__ index.html
   |__ ...
   | /dist
   |__ /css
   |__ /js
   |__ index.html
   | gulpfile.js
   | flightplan.js
   | ...
```

What I'm trying to do is to push only the /dist folder to the server and my configuration now looks like this:

```javascript
plan.local(function(local) {
  local.log('Run build');
  local.exec('gulp build');

  local.log('Copy files to remote host');
  var filesToCopy = local.exec('cd ./dist; find * -type f', {silent: true});
  
  local.transfer(filesToCopy, '~/www/host_path');
});

```

### Issues
1. Setting filesToCopy using 

```javascript
var filesToCopy = local.exec('find ./dist -type f', {silent: true});` 
````
> ends up pushing the whole /dist folder itself

2. Setting it using

```javascript
var filesToCopy = local.exec('cd ./dist; find * -type f', {silent: true});
```

> throw a error like this for each file/directory: 

```shell
localhost > rsync: link_stat "Users/admin/Desktop/myProject/css/styles.min.css" failed: No such file or directory (2).
```
> I can see that the path does not contain de dist/ folder between 'myProject/' and 'css/'. But I have no clue how to fix it using commands within `exec()`.

I also follow your tip on the `with()` method, but I could not realize how to build the files listing using it.

I don't know why, but I'm starting to think I'm over complicating something that should be simple. Thanks again for the attention.

**Comment by pstadler** [comment]
To not over complicate things, how about you'd simply upload your files to a tmp directory and then move these on the remote?

**Comment by cullylarson** [comment]
You can use [transport.with](https://github.com/pstadler/flightplan#transportwithcommandoptions-options-fn) (i.e. `local.with`) to change to a directory before executing commands. Something like this worked for me:

```
    local.with(`cd dist`, () => {
        const filesToCopy = local.exec('find . -type f', { silent: true })

        local.transfer(filesToCopy, '~/www/host_path');
    })
```
