### ISSUE TITLE
rsync: permission denied

### ISSUE THREAD

**Issue by kergeodeta** [pstadler/flightplan#145]
Hi! I'm running Win 8.1 with cygwin. When I call in my nodejs project folder the fly command with the appropriate argument, i get this error: "localhost > Permission denied, please try again." When I call the rsync itself, it requires a password then copies the given files to the remote server without problems. I tried the passwordless authentication too, copied the ssh public key and the rsync it works well again, the files copied to the remote host, but with the fly command I became the same permission denied message. It not requires any password or anything. 
I created a linux guest in vbox, and copied my nodejs project folder on this virtual machine, so all is the same except the os. When I called here the fly command it runs perfectly.

How could I fix this issue? Many thanks for every help (aaaand, sorry for my english, when I wrote something wrong)

Here is the output from the cygwin:
localhost Copy files to remote hosts
localhost $ git ls-files
localhost > app.js
localhost > package.json
localhost ● ok
localhost $ rsync --files-from dce8928af5455d73f1b507a3251c8400 -az --rsh="ssh -p22" ./ kergeodeta@xxx.xxx.xxx.xxx:/home/kergeodeta/test-proj-1469781651157
localhost > Permission denied, please try again.
localhost > Permission denied, please try again.
localhost > Permission denied (publickey,password).
localhost > rsync: connection unexpectedly closed (0 bytes received so far) [sender]
localhost > rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.1]
localhost ● failed (12)
● Command exited abnormally on localhost

**Comment by kergeodeta** [comment]
It was not the flightplan, it was the cygwin. With the start of cygwin the ssh-agent not started. I have to edited the .bash-profile file (http://killtheradio.net/how-tos/ssh-agent-on-cygwin/) and then restart the cygwin. After this I have to added my RSA key and it began to work :-)

**Comment by pstadler** [comment]
Glad you managed to make it work 🍻

**Comment by Benny739** [comment]
I have exactly the same problem, but can't get it working. Could you please explain in detail how you fixed that problem under windows?

Thanks
