### ISSUE TITLE
remote.sudo() error

### ISSUE THREAD

**Issue by CHEWX** [pstadler/flightplan#149]
Hi,

Couldn't find any similar issues in the repo, but I'm getting the following.

```
> stdin: is not a tty
> sudo: no tty present and no askpass program specified
```

I'm assuming this is something to do with the user ? When I FTP in, the user is 507. So I have set `ownerUser: 507` and tried `'www-data`. Also tried parsing the user object to the sudo command. `{user: 507}`.

Thanks

**Comment by pstadler** [comment]
The user that connects to the host needs sudo access as described in the docs.
