### ISSUE TITLE
local.transfer filesToCopy path problem

### ISSUE THREAD

**Issue by zhujun24** [pstadler/flightplan#151]
I wanna rsync one file to server, `filesToCopy` is `['../aaa.conf']` , when `local.transfer(filesToCopy, remoteDir)` ,they will be error `failed: No such file or directory`,because that rsync file path is current path connect `filesToCopy`,just like `/code/project/test/../aaa.conf` not `/code/project/aaa.conf`

**Comment by DuanPengfei** [comment]
I also with the same problem. `local.transfer('../app/', REMOTE_PROJECT_CODE_PATH);` got error `rsync: link_stat "/tt/deploy/app" failed: No such file or directory (2)`, the correct path should be `/tt/app` not `/tt/deploy/app`, the `flightplan.js` in the `/tt/deploy/` folder.

**Comment by pstadler** [comment]
Hey there.

Unfortunately this is limitation of rsync. You could try to work with absolute paths or create a tar file (probably in /tmp), transfer this to the remote servers, untar it and continue from there. This has several advantages over copying a bunch of single files.

**Comment by DuanPengfei** [comment]
By the way, why use the tmp file instead of direct upload origin file? What are the benefits of doing so?

**Comment by pstadler** [comment]
This is the only way to ensure compatibility with various operating systems and rsync version. See [here](https://github.com/pstadler/flightplan/releases/tag/0.4.2)

**Comment by DuanPengfei** [comment]
👍

**Comment by zhujun24** [comment]
Copy file instead of origin file to transfer is hack, but it's the only way to resolve it.
