### ISSUE TITLE
Flightplan runtime object is empty during dynamic hosts configuration 

### ISSUE THREAD

**Issue by Glebka** [pstadler/flightplan#153]
It would be nice to retrieve command line arguments, task and target names from the Flightplan runtime object during the dynamic hosts configuration. But, unfortunately, this object is empty.

For example, I am using "production" target with two hosts: service1.host.com and service2.host.com. Each host serves one microservice with some business logic. I have to write flightplan with two tasks: "start"and "stop" and I want to have different order of service startup and shutdown.
Without information about current running task I can't manage the order of hosts during dynamic hosts configuration. So "start" and "stop" tasks will be performed on the hosts in that order they originally were registered.

**Comment by pstadler** [comment]
This has been released with [0.6.15](https://github.com/pstadler/flightplan/releases/tag/0.6.15)
