### ISSUE TITLE
Bad option: --harmony_arrow_functions if run from `npm run`

### ISSUE THREAD

**Issue by ruslankonev** [pstadler/flightplan#157]
![image](https://cloud.githubusercontent.com/assets/2588730/21452827/ba98ccd2-c91a-11e6-9226-9427b2890a26.png)

![image](https://cloud.githubusercontent.com/assets/2588730/21452838/cb370770-c91a-11e6-9402-1012b86f6246.png)

**Comment by pstadler** [comment]
This is not related to flightplan. Please note that `./node_modules/fly` is not related to flightplan. Your setup is probably conflicting with [fly](https://github.com/flyjs/fly). See also #96.
