### ISSUE TITLE
Optimized localhost target?

### ISSUE THREAD

**Issue by rmhubley** [pstadler/flightplan#159]
Question:  I would like to have the option of switching a target to the localhost but without the overhead of having flightplan attempt to use SSH/SCP etc to move files around.  Is there a way to define the target in such a way that remote operations become local ones?

**Comment by pstadler** [comment]
I'm not quite sure if I fully understand your question, but you can use `plan.local()` to execute commands on your current host. If you have commands which should be executed on both local and remote hosts, simply put those in a function:

```js
function foo (transport) {
  // your commands here
}

plan.local(foo);
plan.remote(foo);

```
