### ISSUE TITLE
Run local-only flights without specifying remote on command-line

### ISSUE THREAD

**Issue by ravi** [pstadler/flightplan#160]
I have searched around and I am sure an answer exists, but I cannot find it. So, with apologies, a question: if I have a flightplan that has only local tasks, specifying a target on the command-line does not make sense. However `fly --flightplan localflight.js` returns an error. Is there a way to do this right? Right now, I am using a hack: `fly local --flightplan localflight.js` with `local` configured to be `localhost`. But that still causes an SSH attempt and failure being logged.

**Comment by pstadler** [comment]
Unfortunately, the only way this can be done currently is to specify an empty target.

```js
// flightplan.js
plan.target('local');

// execute:
fly local
```

**Comment by pstadler** [comment]
Follow up: #161

**Comment by ravi** [comment]
Ah, an empty target works for me, it was the 'localhost' part in my solution that was bothering me.
