### ISSUE TITLE
Looking for help / maintainers

### ISSUE THREAD

**Issue by pstadler** [pstadler/flightplan#162]
As my time is currently limited I'm looking for co-maintainers, means people willing to actively push new features and potentially do some bigger refactoring. Furthermore I'm not really using this project due to different requirements (CI/CD).

You should have at least a minimal track record in publishing / maintaining JavaScript libraries or projects.

Feel free to add a comment here or contact me directly by email (see https://pstadler.sh)

> A couple of ideas for the future:
> - Improve API to be more powerful, e.g. task dependencies instead of top-down execution
> - Improve remote copying of files (using maybe scp instead of rsync?)
> - Replace fibers with async-await when the time is ripe

**Comment by jeanfredrik** [comment]
Hi @pstadler 
I'm working at [Whitespace](https://github.com/whitespace-se), where we build all kinds of websites using different technologies, but what they all have in common is that we’re using Flightplan to do deployments. We are therefore deeply invested in the continuation of this package and would love to help you out.

**Comment by pstadler** [comment]
Hey Fredrik. I granted you access to the repository. Feel free to work on it. As soon as there's something to be released, I'm happily grating you access to npm as well.

I won't have time to give support here, but drop me an email or whatever if you want to discuss something.

Cheers,
Patrick

**Comment by jeanfredrik** [comment]
That’s great! Me and my colleagues will be looking through the open issues and create a backlog shortly.

**Comment by rmplbv** [comment]
Sorry to ask, but is this project dead?
I really would like to use this package, but with the last commit 3 years ago and the last answer to this issue a half year old, I'm afraid i'm about to invest into a dead end.

**Comment by pstadler** [comment]
pretty much dead, yes.
