### ISSUE TITLE
Broken on node 4.x due to node-fibers dependency removing node 4.x binary

### ISSUE THREAD

**Issue by sdd** [pstadler/flightplan#166]
It looks like node-fibers has removed node 4.x binaries from their latest release, but only bumped the package version.

This has resulted in flightplan being unable to install on node 4.x, breaking our deployment process.

We can't just add fibers@1.0.15 to the package.json as node 4.x does not have npm 3.x.

Can you please release a version that pins fibers to 1.0.15 for people who for one reason or another are stuck on node 4.x? 

See https://github.com/laverdet/node-fibers/issues/342

**Comment by pstadler** [comment]
Thanks for reporting this. 0.6.17 has been released. 

- Release notes: https://github.com/pstadler/flightplan/releases/tag/0.6.17
- Travis builds: https://travis-ci.org/pstadler/flightplan/builds/239520959

**Comment by sdd** [comment]
Awesome! Thanks you very much for the super quick response.
