### ISSUE TITLE
Please support fibers@2.0.0 for Windows users on Node 8

### ISSUE THREAD

**Issue by natesilva** [pstadler/flightplan#168]
In #167 the `fibers` dependency was pinned to version `1.0.15` for Node version 4 compatibility.

However, there isn’t a pre-compiled Windows binary for that version of `fibers` and Node version 8. Meanwhile, `fibers` version `2.0.0` does have a Node version 8 binary for Windows.

According to the [commit log](https://github.com/laverdet/node-fibers/commit/3566b274bc2e863d960f3b3f68cd68301dcf3497) there are no changes in `2.0.0` except for Node 4 compatibility.

So… would it be possible to add a `dist-tag`, maybe `flightplan@next`, that would use `fibers` `2.0.0`? Or, alternately, put Node v4 support under a tag like `flightplan@legacy` or `flightplan@node4` etc.

That would let me roll this out to my Windows developers, we’ve been holding off on implementing flightplan.

**Comment by natesilva** [comment]
We’re going to use `windows-build-tools` from npm. It would still be nice to have a binary, but that works for us right now!

**Comment by pstadler** [comment]
Hi Nate, you might want to comment on this Issue: https://github.com/laverdet/node-fibers/issues/342
