### ISSUE TITLE
fly VS fly conflict 

### ISSUE THREAD

**Issue by thierryc** [pstadler/flightplan#169]
# fly VS fly conflict 

https://github.com/pstadler/flightpla
```
# run a flightplan (`fly --help` for more information)
$ fly [task:]<target> [--flightplan flightplan.(js|coffee)]
```

https://github.com/flyjs/fly

I use both but both CLI have the same name !

```
fly [options] <tasks>
fly --mode=parallel task1 task2 ...
``` 

How to deal with both in the same project ? 

Add flightplan as an alias to fly ?

Rename fly cli to flightplan and add an alias ( ln -s ) to be back compatible ?

**Comment by pstadler** [comment]
See: https://github.com/pstadler/flightplan/issues/96

**Comment by thierryc** [comment]
thank you
