### ISSUE TITLE
Permission denied when running sudo command

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [pstadler/flightplan#176]
Hello.

Have this command to run 

    remote.sudo('service nginx restart', {user: 'dev'})

My `dev` user has sudo rights:

    ~$ groups dev
    dev : dev sudo

When I try to run this command, it throws me this error:

     $ echo 'service nginx restart' | sudo -u dev -i bash
      > Failed to restart nginx.service: Interactive authentication required.

I don't understand, why this sudo command does not promt manual password input. `transfer` automatically prompts that kind of input.

**Comment by pstadler** [comment]
Please refer to the following section in order to use passwordless authentication when running `sudo`: https://github.com/pstadler/flightplan#transportsudocommand-options--code-int-stdout-string-stderr-string
