### ISSUE TITLE
Transfer files from parent folder

### ISSUE THREAD

**Issue by renarsvilnis** [pstadler/flightplan#177]
Ability to transfer "rsync" files from the parent directory.

I have a use case I have a deployment script, that lives in separate repo because it's only used for local development.

I want the script to take files from outside of repo, seperate server and frontend repos and deploy them to an ec2 instance.

I have gotten so far that I proved relative paths to the files I need.

```
'../relative-server-repo-path/api/amazon.js',
'../relative-server-repo-path/api/client.js',
'../relative-server-repo-path/config/devices.js',
'../relative-server-repo-path/config/cors.js',
'../relative-server-repo-path/config/logger.js',
'../relative-server-repo-path/config/oauth.js',
'../relative-server-repo-path/config/redis.js',
'../relative-server-repo-path/config/sequelize.js',
'../relative-server-repo-path/config/session.js',
...
```

But once rsync does it stuff, it just drops the `..` parent directory part of the string. Going trough logic verified that the temp file before rsync contains the parent directory path. It just gets ignored by rsync.

Is there a flag that allows it? Or just an rsync limitation?

## Update #1
Looks like it's by rsync design.

> The filenames that are read from the FILE are all relative to the source dir -- any leading slashes are removed and
    no ".." references are allowed to go higher than the source dir.
> https://ss64.com/bash/rsync_options.html

I would workaround it by copying the files I need to `tmp` dir and transfering it, but still the issue of the wrong "cwd" would be present as rsync command sets from the deployment script

`rsync --files-from <tmp-filelist-path> -azR --rsh="ssh -p22 -i <path-to>.pem" ./ <server-destionation-url-path>`

**Comment by pstadler** [comment]
You can always create a tar file and simply copy this over.

**Comment by pstadler** [comment]
Please re-open if this is still a problem.

**Comment by renarsvilnis** [comment]
@pstadler Thanks, forgot about something that simple, I just finished overengineering the issue, by copying needed files from multiple to tmp folder in the deployment repo and using the transfer as usual.
