### ISSUE TITLE
Remote context in unexpected state

### ISSUE THREAD

**Issue by mattfordham** [pstadler/flightplan#36]
I cannot seem to run some commands via "exec" that I can run on the server directly. For example, when I run a command like this...

`remote.exec("npm install")`

I am getting a "bash: npm: command not found" error, while running the command via ssh works fine. 

Another clue, is that running `node -v` indicates the version of Node that was installed by default on the system, as opposed to the NVM installed version I get when ssh'ing in. 

Also, FWIW, "sudo" is not necessary to run these command on the server, and I am using flightplan with the same user I ssh in with.

Any idea if this a bug or a step I am missing?

**Comment by zolzaya** [comment]
Hello @mattfordham ,

I have a exact same problem. I need a run `nvm use default` command before I install dependencies. How did you solve it?

**Comment by slavafomin** [comment]
@zolzaya take a look at [my answer on SO](http://stackoverflow.com/a/37710790/1056679).
