### ISSUE TITLE
Provide way to delete release on disaster

### ISSUE THREAD

**Issue by dasuchin** [pstadler/flightplan#37]
It would be great to have a way to delete the release that I'm pushing in case of disaster. Currently there is a disaster function, but I can't find a way to pass in remote and delete the current release.

**Comment by fluxsaas** [comment]
i have following task to cleanup releases:

    plan.remote 'cleanupReleases', (transport) ->
      releases = []
      transport.with "cd #{plan.runtime.options.releases_dir}", ->
        releases = _.compact(transport.ls('-t').stdout.split('\n'))

      directories = _.rest(releases, plan.runtime.options.keep_releases)

      directories_str = _.map(directories, (release) ->
        "#{plan.runtime.options.releases_dir}/#{release}"
      ).join(" ")

      if _.any(directories_str) then transport.rm('-rf ' + directories_str);


you need to set `keep_releases: 3` in `plan.target` config.
