### ISSUE TITLE
Rsync issue on Windows - hostname not same as transfer hostname

### ISSUE THREAD

**Issue by inuwan** [pstadler/flightplan#42]
I have cwRsync on Window.  In my flightplan I have:

plan.remote('windows', function(remote) {
	remote.log('Preparing destination...');
	remote.exec('rm -rf ' + remoteWindowsPath);
	remote.exec('mkdir ' + remoteWindowsPath);
});

// fly windows:<destination>
plan.local('windows', function(local) {
	local.log('Copy files to remote hosts');
	var curDir = local.exec('chdir').stdout + '\\';
	local.transfer(curDir + 'myfile', remoteWindowsPath + '/build');
})

I get the following results:

myremotehost.com ● Preparing destination...
myremotehost.com $ rm -rf ~/build
myremotehost.com ● ok
myremotehost.com $ mkdir ~/build
myremotehost.com ● ok

localhost ● Copy files to remote hosts
localhost $ chdir
localhost > C:\src
localhost ● ok
localhost $ rsync --files-from C:\Users\Ken\AppData\Local\Temp\e228633a-7454-46df-8f52-bf9ad0c72323 -az --rsh="ssh -p22"
 ./ me@myremotehost.com:~/build
localhost > --files-from hostname is not the same as the transfer hostname
localhost > rsync error: syntax or usage error (code 1) at main.c(1293) [sender=3.1.1]
localhost ● failed with exit code: 1
✈ Error: `rsync --files-from C:\Users\Me\AppData\Local\Temp\e228633a-7454-46df-8f52-bf9ad0c72323 -az --rsh="ssh -p22" ./ me@myremotehost.com:~/build` failed on localhost

The file C:\Users\Me\AppData\Local\Temp\e228633a-7454-46df-8f52-bf9ad0c72323 contains:

       C:\src\myfile

I cannot determine how to fix the rysync "--files-from hostname is not the same as the transfer hostname" error.  I tried:

rsync myfile -az --rsh="ssh -p22" ./ me@myremotehost.com:~/build

And that transfers the file ok.  So it appears the issue is could be resolved by eliminating the --files-from option.

**Comment by DeltaMeter** [comment]
Ok, so I ran this
 "rsync --files-from /cygdrive/c/cygwin64/tmp/3704f930-ac80-403c-beb3-c5e0605b988b -az --rsh="ssh -p22 -i D:\path_to_keys\key.pem" ./ ubuntu@host:~/" 

And it copied all the files to my web server. So is that it? I just "node bin/www" and that's all I need to do?

**Comment by joshunger** [comment]
You could re-define your TMPDIR -

```javascript
if (process.env['TMPDIR'] === 'C:\\cygwin\\tmp') // or whatever logic you want
{
	process.env['TMPDIR'] = '/tmp';
}

var plan = require('flightplan');
```

**Comment by ami44** [comment]
Hello

Why not use https://www.npmjs.com/package/scp2 !

scp2 is greatly powered by ssh2, implemented the scp in a sftp way.
It is written in pure javascript, and should work on every OS, **even Windows**. Nodejs (v0.8.7 or newer) is required to make it work.

ami44

**Comment by Marcel-Robitaille** [comment]
I am still having problems. Could someone please help me?

**Comment by joshunger** [comment]
What's the exception?  What is your code?

**Comment by Marcel-Robitaille** [comment]
Here is my flightplan file:
```javascript
var plan = require('flightplan');

plan.target('production', [{
    host: '50.87.144.81',
    username: 'mjr',
    port: 2222,
    agent: process.env.SSH_AUTH_SOCK
}]);

plan.local(function(local) {
    var filesToCopy = local.exec('git ls-files', {silent: true});
    local.transfer(filesToCopy, 'public_html/foyerecolecsrs.ca/');
});
```

Here is the error I get:
```
--files-from hostname is not the same as the transfer hostname
rsync error: syntax or usage error (code 1) at main.c(1293) [sender=3.1.1]
```

I am running windows with cwRsync.

**Comment by pstadler** [comment]
This is a known issue. Will try to solve it with the next release.

**Comment by pstadler** [comment]
[0.6.2](https://github.com/pstadler/flightplan/releases/tag/0.6.2) should fix this once and for all. Please let me know if there's still a problem. Thanks @gfilardo for suggesting and implementing this fix.

**Comment by Marcel-Robitaille** [comment]
I am still getting an error when I run flightplan:
```
localhost $ rsync --files-from a34f38ad757af8d477e75eb930a5205b -az --rsh="ssh -p2222" ./ <my user>@<my host>:public_html/
localhost > usage: ssh [-1246AaCfghkNnqsTtVvXxY] [-b bind_address] [-c cipher_spec]
localhost >            [-D port] [-e escape_char] [-F configfile] [-i identity_file]
localhost >            [-L port:host:hostport] [-l login_name] [-m mac_spec] [-o option]
localhost >            [-p port] [-R port:host:hostport] [user@]hostname [command]
localhost > rsync: connection unexpectedly closed (0 bytes received so far) [sender]
localhost > rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.1]
localhost ● failed (12)
● Command exited abnormally on localhost

**Comment by gfilardo** [comment]
What shell are you using? I have experienced the same problem using GitBash. It never occurred to me using flightplan from cmd or powershell.

**Comment by Marcel-Robitaille** [comment]
I am using cmd.exe

**Comment by pstadler** [comment]
I wanted to setup a VM with these tools once but I failed with node.js/npm. Do you have a good guide for that?

**Comment by Marcel-Robitaille** [comment]
> I wanted to setup a VM with these tools once but I failed with node.js/npm. Do you have a good guide for that?

Unfortunately, I do not. I have not had very good luck with VMs in the past.

**Comment by pstadler** [comment]
I actually know how to set up a VM, but not how Windows users use node.js and all the npm fancy on their machines.

**Comment by seybsen** [comment]
@pstadler I could provide a guide for windows users soon. Setting up flightplan... no... sorry, setting up ssh on windows' powershell or cmd in combination with flightplan was a long journey for me. I ended up using powershell 4.0, scoop, node, openssh, (cw-)rsync, pageant and puttygen.
(P.S.: I did not use `.transfer()` from flightplan but `local.exec('rsync ...')`)

    plan.target('staging', {
    	host: 'example.com',
    	username: 'myuser',
    	privateKey: process.env.HOMEDRIVE + process.env.HOMEPATH + '\\.ssh\\id_rsa',
    	agent: 'pageant'
    });

the transfer looks something like this for me:

    local.exec('rsync -rz --delete --rsh \'C:\\cwrsync\\bin\\ssh.exe -o StrictHostKeyChecking=no\' ./ ' + host.username + '@' + host.host + ':' + config.projectDir, { silent: true });

@Marcel-Robitaille I also fixed this error once: for me it occured when I tried using cwrsync with the ssh.exe provided by openssh (or git) and not the one that comes with cwrsync. Check your path environment variable and try putting cwrsync before openssh or git.

**Comment by pstadler** [comment]
@seybsen wow, that sounds like torture. Let me know if you're going to write a guide or something; I've yet to decide whether it's worth the trouble of setting up the whole env on a Windows VM. Anyway, thanks for dropping a couple of lines here.

**Comment by Marcel-Robitaille** [comment]
@seybsen Thanks for the suggestion. I switched to rsync's ssh. Now I get the following error:
```
localhost > Host key verification failed.
localhost > rsync: connection unexpectedly closed (0 bytes received so far) [sender]
localhost > rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.1]

**Comment by seybsen** [comment]
@Marcel-Robitaille that's why I added `-o StrictHostKeyChecking=no` to my custom rsync command. But you can try adding the servers you want to connect to manually to your `known_hosts`-file (should be in your `.ssh/`-folder)

**Comment by pstadler** [comment]
I'd suggest you manually ssh into the remote hosts (if this is even possible, don't know about cwRsync and "their ssh client"), in order to get the dialog asking you to confirm signatures. But yeah, placing `StrictHostKeyChecking: no` in the right file will do the trick as well.

**Comment by Marcel-Robitaille** [comment]
Ok, I think I am getting close. I have changed my flightplan.js file to this:
```javascript
local.exec('rsync -rz --rsh \'\"C:\\Program Files\\rsync\\ssh.exe\" -p2222 -o StrictHostKeyChecking=no\' ./ <user>@<host>:<path>');
```
I am prompted for my password. After I enter it, I get:
```
rsync: failed to open "<all the files>", continuing: Permission denied (13)
