### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by Serhioromano** [pstadler/flightplan#55]
I have connection failed but very strange.

>  Error connecting to 54.145.**.** Error: Authentication failure. Available authentication methods: publickey,gssapi-keyex,gssapi-with-mic,password
1. It makes `rsync`. SO the connection to SSH must be ok.
2. When i connect in terminal with `ssh deploy@10.10.10.10` it works perfect without require login based on default RSA key.
3. This is how I setup connection
   
   ``` js
   plan.target('production', {
   host: '54.145.**.**',
   username: 'deploy',
   agent: process.env.SSH_AUTH_SOCK
   });
   ```

So this is what I get.
![2014-12-23_15-19-32](https://cloud.githubusercontent.com/assets/650741/5535345/9e08e99c-8ab7-11e4-9816-fef4b06bc7a7.png)

**Comment by pstadler** [comment]
Here's an article regarding adding keys to `ssh-agent` for passwordless authentication: https://help.github.com/articles/working-with-ssh-key-passphrases/

**Comment by neilhanekom** [comment]
Hi Guys, 

I am having the same issue here. I have added my rsa_id keys prior to this. So I can connect to my server without password.

Now adding privateKey key/pair to the production object as you have suggested gives me the following line:

Warning: Identity file /Users/neilhanekom/.shh/id_rsa not accessible: No such file or directory.

This is probably a permission/role issue. But I would greatly appreciate if anyone can help me on this.

**Comment by pstadler** [comment]
Try .ssh/ instead of .shh/




Cheers,

Patrick

**Comment by romanostolosh-devpronet** [comment]
Hi everyone,

Cool tool. Just wanted to say that.

One thing that I found inconvenient though is that you still have to provide privateKey, username and so on, regardless the fact that we may have fully functional and configured ssh client localy.. 

What I'm trying to say is that it would be really cool if we would able to make use of ~./ssh/config file that user may already have configured

Is it even technically possible?

Thank you in andvance

**Comment by pstadler** [comment]
@romanostolosh-devpronet check this: https://github.com/mscdex/ssh2/issues/70

**Comment by romanostolosh-devpronet** [comment]
@pstadler thanks!
Sounds like a plan :)

**Comment by ArtemMedvedev** [comment]
I had error with authentication, sounds like "All configured authentication methods failed".
But I solved this by adding path to the privatekey in the connection config.

```javascript
plan.target('staging', [{
        host: host,
        username: username,
        privateKey: 'path/to/the/.ssh/id_rsa',
        agent: process.env.SSH_AUTH_SOCK
    }
]);
```

**Comment by ALEXOTANO** [comment]
> I had error with authentication, sounds like "All configured authentication methods failed".
> But I solved this by adding path to the privatekey in the connection config.
> 
> ```js
> plan.target('staging', [{
>         host: host,
>         username: username,
>         privateKey: 'path/to/the/.ssh/id_rsa',
>         agent: process.env.SSH_AUTH_SOCK
>     }
> ]);
> ```

Works perfectly, just careful not tu use ~/.ssh/key use the whole path.

**Comment by MohamedNedal** [comment]
> I had error with authentication, sounds like "All configured authentication methods failed".
> But I solved this by adding path to the privatekey in the connection config.
> 
> ```js
> plan.target('staging', [{
>         host: host,
>         username: username,
>         privateKey: 'path/to/the/.ssh/id_rsa',
>         agent: process.env.SSH_AUTH_SOCK
>     }
> ]);
> ```

Where should I write this please?
