### ISSUE TITLE
How to get user password?

### ISSUE THREAD

**Issue by Serhioromano** [pstadler/flightplan#58]
I have somethign like this

``` js
plan.target('production', {
    host:     '54.145.*.*',
    username: 'deploy',
    password: '*****',
    agent:    process.env.SSH_AUTH_SOCK
});
```

But I do not want to have password there. i want to be asked for password during `fly` command execution. That is because this file is a part of Github repository and I do not what to reveal SSH user name and password.

I know about `transfer.prompt()` but how can I update data in target?

**Comment by creynders** [comment]
Is there no other way to do this? I'm looking for a fully automated deployment strategy, i.e. I give credentials to a developer and all he needs to do is clone the repo, run make/grunt/whatever and it gets built and deployed, prompting the developer for specific info.

**Comment by Serhioromano** [comment]
Why @creynders ? Flightplan is exactly for this purpose. What make you unsure?

**Comment by pstadler** [comment]
You have two options:
a) Put the public keys of your team members to the remote hosts, so they can authenticate without a password. This is the preferred way.
b) Share the login password of the remote hosts with your team. As soon as they try to establish a connection, the hosts will prompt them to enter the password. This is obviously less secure and less comfortable than public key authentication.

**Comment by creynders** [comment]
@pstadler ok thanks, that's what I needed to know!
