### ISSUE TITLE
'rsync' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by DeltaMeter** [pstadler/flightplan#59]
I'm running on Windows, so do I have to install cygwin to fix this problem?

**Comment by pstadler** [comment]
Yes, I think so. Or you manually copy the files using an available command on Windows. How do you run flightplan without cygwin? Does this even work? See also #42

**Comment by Marcel-Robitaille** [comment]
You can install rsync on windows. https://rsync.samba.org/download.html
