### ISSUE TITLE
Doesn't work with dash as remote shell (dropbear as remote ssh server)

### ISSUE THREAD

**Issue by solshark** [pstadler/flightplan#60]
I use flightplan to deploy my project to Raspberry Pi. In order to optimize RPi I switched from bash to dash.
Connecting over ssh it works fine, PATH available and no issues finding commands. But trying to deploy using flightplan I'm getting issue:
```
pi Install dependencies
pi $ npm --production --prefix /data/www/aquacontroller-11-01-2015-00-09-41 install /data/www/aquacontroller-11-01-2015-00-09-41
pi > bash: npm: command not found
pi ● failed (127)
● Command exited abnormally on pi

```

**Comment by pstadler** [comment]
Seems like `dash` is not your user's login shell:
```
pi > bash: npm: command not found
```
Make sure you set the right `PATH` for bash, or change the login shell to `dash`.

**Comment by solshark** [comment]
You right. I've changed shell to dash but issue still here:
```
pi Install dependencies
pi $ npm --production --prefix /data/www/aquacontroller-11-01-2015-14-26-05 install /data/www/aquacontroller-11-01-2015-14-26-05
pi > dash: 1: npm: not found
pi ● failed (127)
● Command exited abnormally on pi
```

And same time PATH is correct and logging in via SSH I'm able to call commands from /usr/local/bin with dash.

**Comment by solshark** [comment]
Okay, it's not about dash/bash. Seems like it's connected to dropbear instead openssh.

**Comment by solshark** [comment]
Yeah, see below:
- from **remote** machine:
```
ssh pi "env | grep PATH"
PATH=/usr/bin:/bin
```

- from **local** pi shell:
```
$ env | grep PATH
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
```

**Comment by pstadler** [comment]
Is this still a problem or can I close it?

**Comment by solshark** [comment]
Well, it's still a problem. Would be great if someone could find workaround. For simple tasks I do like this:
```coffeescript
remote.exec "export PATH='/usr/local/bin:$PATH' && pm2 reload aquacontroller"
```

But it doesn't work for tasks like 'npm install'

**Comment by pstadler** [comment]
Maybe this is helpful: http://www.linuxquestions.org/questions/debian-26/how-to-configure-dash-745494/

**Comment by solshark** [comment]
Actually, it's not about dash. It's about dropbear used instead of openssh. Solution might be to recompile dropbear, but I wondered if someone knows another way to solve it.

**Comment by pstadler** [comment]
Try this: 

```javascript
remote.exec("pm2 reload aquacontroller", {exec: {pty: true}});
```

**Comment by solshark** [comment]
Nope, unfortunately still getting 
```
pi > dash: 1: pm2: not found
```

**Comment by pstadler** [comment]
Any news here?

**Comment by pstadler** [comment]
I still believe that this is a dash issue. Please refer to the "Invocation" section of http://linux.die.net/man/1/dash
Expand the PATH in `.profile` to include /usr/local/bin and try with and without passing `{exec: {pty: true}}` when running commands.

If this still doesn't work then there's only one way to solve this: `chsh` to another login shell... or it is indeed a problem with Dropbear.

Please let me know your findings here.

**Comment by solshark** [comment]
Hi, sorry for delay with response, I've been pretty busy, but now I likely will be able to spend some time today or tomorrow on that issue.
