### ISSUE TITLE
Remote and Local File Support

### ISSUE THREAD

**Issue by tlperkins** [pstadler/flightplan#61]
I like what I see in Flightplan and I'm a heavy user or Fabric.  I'm trying to figure out how to cover the basic file handling functionality with Flightplan.  I notice that some basic primitives are missing.  For example I'd like to to be able to simply pipe a stream to a remote file and vice versa.  That allow me to do 100% of what I need to do in terms of build higher level primitives.  In general here is what I'm thinking:

http://docs.fabfile.org/en/1.10/api/contrib/files.html

upload_template is of interest as well as "conditional" append

**Comment by pstadler** [comment]
You can write/modify files on the remote host like this:

```javascript
// Option 1
plan.local(function(local) {
  local.transfer('templates/foo.config', '/tmp');
});

plan.remote(function(remote) {
  remote.exec('sed -e "s/\${var1}/bar1/" -e "s/\${var2}/bar2/" /tmp/templates/foo.config');
});

// Option 2
plan.remote(function(remote) {
  var file = fs.readFileSync('./templates/foo.config').toString();
  file = file.replace('${var1}', 'bar1')
         file.replace('${var2}', 'bar2')
             .replace(/'/gi, "\\'")
             .replace(/"/gi, "\\\"")
             .replace(/\n/gi, "\\n");
  remote.exec('printf "' + file + '" > /tmp/foo.config');
});
```

And to fetch the contents of a remote file and write it to your localhost:

```javascript
plan.remote(function(remote) {
  var file = remote.exec('cat /tmp/foo.config');
  fs.writeFileSync('./foo.config', file.stdout);
});
```

How would you like to perform this actions instead? (i.e. if you could design an interface, how would it look like?)
