### ISSUE TITLE
Stop task when killing

### ISSUE THREAD

**Issue by Carlangueitor** [pstadler/flightplan#62]
I'm running a task for running a expressjs server on a vagrant machine, something like this:

    plan.remote('runserver', function(transport) {
      transport.with('cd myapp', function() {
        transport.exec('node server.js')
      });
    });

When I type Ctrl+C to stop the server, flightplan closes but the task doesn't and when i want to run the task again it crashes because the previous process is still running.

At now, I'm killing the process manually in the task, but it would be great if this happen automatically.

**Comment by pstadler** [comment]
Try this for now:

```javascript
plan.remote('runserver', function(transport) {
  transport.with('cd myapp', function() {
    transport.exec('node server.js', { exec: { pty: true } });
  });
});
```

I'm thinking about allocating a PTY by default.

**Comment by Carlangueitor** [comment]
Cool, it works! Thanks!
