### ISSUE TITLE
liftoff 2x / v8flags 2x released

### ISSUE THREAD

**Issue by tkellen** [pstadler/flightplan#63]
Heya, this is just a friendly note to let you know that a new version of Liftoff and some of the dependencies commonly used in conjunction with it have been released. This release adds better support for situations where your user's configuration files are written using features behind a v8 flag (e.g. `--harmony`). Windows users and `io.js` users should see less issues if you upgrade!

Some helpful links:
https://github.com/tkellen/node-liftoff/blob/master/UPGRADING.md#100---200
https://github.com/tkellen/node-v8flags/blob/master/README.md#example
https://github.com/tkellen/node-hacker/blob/master/bin/hacker.js#L10-L14

Thanks!

**Comment by pstadler** [comment]
Will upgrade soon. Thank you Tyler.
