### ISSUE TITLE
io.js compatibility

### ISSUE THREAD

**Issue by pstadler** [pstadler/flightplan#64]
Currently waiting for [node-fibers](https://github.com/laverdet/node-fibers) to add support for io.js.

Related:
- https://github.com/laverdet/node-fibers/issues/203
- https://github.com/iojs/io.js/issues/456

**Comment by ChrisAlvares** [comment]
If anyone is looking for a workaround, I was able to get this to run in iojs by running the following commands:
If you already haven't, then install n
```
sudo npm install n -g
```
then inside your project
```
sudo n latest
npm install flightplan
sudo n io latest
cd node_modules/flightplan/node_modules```
rm -rf fibers
git clone -b stack-guard git@github.com:laverdet/node-fibers.git
mv node-fibers fibers
cd fibers
npm install
```

cd back into your project directory and ```fly deploy:production``` should work

**Comment by pstadler** [comment]
Thanks Chris.

**Comment by pstadler** [comment]
Verified with node 4.2.x
