### ISSUE TITLE
Need support for PHP frameworks

### ISSUE THREAD

**Issue by mainalikishan** [pstadler/flightplan#65]
flightplan uses git-ls-files. Which means it ignores files and folder in .gitignore...but in framework like laravel, symphony...there are vendor files...which are ignored in git. But in production if server doesn't have composer setup or support we need to  upload vendor folder. 

So, if flightplan can make optional config to upload or not vendor folder. It would be great. And lot of more  developer base could use this.

**Comment by Amrit01** [comment]
:+1:

**Comment by chaudharyramesh** [comment]
+1 (y)

**Comment by joshilomas** [comment]
:+1:

**Comment by Kokil** [comment]
(y)

**Comment by pstadler** [comment]
This is already possible. Flightplan doesn't use `git ls-files`, it's only used in the example. You can pass whatever you want to `transfer()`:

```javascript
// In a typical node.js project, node_modules is in .gitignore and "git ls-files" won't list it.
var files = local.exec('git ls-files');
// If the node_modules folder should be transferred as well, you can do this:
var files = local.exec('git ls-files;find node_modules -type f');
// Transfer some compiled assets as well:
var files = local.exec('git ls-files;find node_modules -type f;find assets -type f');
```

That's not all, please make sure to check out this: https://github.com/pstadler/flightplan#files-argument
