### ISSUE TITLE
Support Task Flow (Dependency)

### ISSUE THREAD

**Issue by oliverzy** [pstadler/flightplan#67]
Hi,

I think flightplan is cool, but it seems that no direct way to run multiple tasks that have dependency between them.

For example, I have a "build" task and "deploy" task, the "deploy" task must be run after the "build" task. If I can define dependencies between tasks just like Grunt/Gulp/Shipit, this issue will be resolved elegantly.

I found https://github.com/orchestrator/orchestrator is a great library to do this thing and it has already used by Gulp/Shipit, should be reliable enough.

**Comment by pstadler** [comment]
Will look into this in the near future. Thanks for your feedback.

**Comment by pstadler** [comment]
I'm closing this in favor of #66. Please continue the discussion there.
