### ISSUE TITLE
Preserve UNIX permissions by executing rsync in archive mode?

### ISSUE THREAD

**Issue by desmondhwong** [pstadler/flightplan#69]
For `transfer()`, `rsync` is executed in verbose mode (`-vv`). How can `rsync` be executed with archive (`-a`)? One issue I had was that unix permissions were not preserved after I deployed to a target server.

**Comment by pstadler** [comment]
`transfer()` is always executed with the `az` flags. See here: https://github.com/pstadler/flightplan/blob/master/lib/transport/shell.js#L99
