### ISSUE TITLE
prompt and --no-color

### ISSUE THREAD

**Issue by ami44** [pstadler/flightplan#70]
Hello

When you exec ``fly staging --no-color`` and use ``local.prompt('Enter value:');`` then fly prompt with gray color. It must be without color normally.

Thank, Ami44

**Comment by pstadler** [comment]
Thanks for reporting, will be fixed in the next days.

**Comment by ami44** [comment]
Thank

**Comment by pstadler** [comment]
0.6.1 has been released and should fix this problem :beers:
