### ISSUE TITLE
Use with gitlab-ci

### ISSUE THREAD

**Issue by snumb130** [pstadler/flightplan#72]
Using flightplan locally and everythings runs fine.  When trying to setup gitlab-ci job to run, it fails on any remote commands.  Connection is never made.  `local.transfer` works fine, but when setting up `plan.remote` the connection fails with the following error

```
Error connecting to XXX.XXX.XXX.XXX: Error: Authentication failure. Available authentication methods: publickey,password
```

Has anyone had any luck here.  I'm not sure why the transfer works fine but remote commands will not with the same user.

**Comment by pstadler** [comment]
Is this still an issue or could you solve it? I think your private key is not recognized on the host running flightplan. Strangely enough the connection rsync connection seems to work fine. Do you need to enter a password when using `local.transfer()`?

**Comment by snumb130** [comment]
I never did get it solved.  It would work with a password.  I believe I was not using the right key.  I will try it again soon and dig to make sure key is correct.
