### ISSUE TITLE
Transfer does not recurse deeper than 1 directory

### ISSUE THREAD

**Issue by creynders** [pstadler/flightplan#73]
I'm a bit astonished nobody else has (reported) this issue, but if I try to use flightplan as-is it will only transfer a directory and its contents (including creation of sub-directories), but not recurse into these sub-directories.

E.g. I've got a setup `foo/bar/qux` and I declare `foo/` as a source it will transfer `foo` and `bar`, but the latter one is empty. If I declare `foo` as a source it will only create an empty `foo` directory.

This is because `rsync -av src/ dest` functions differently than `rsync -av --from-file=temp.txt ./ dest` (even if `temp.txt` contains `src/`). The latter being the command used by flightplan. 

Am I missing something? Or is this a Mac OS X thing? Or?

**Comment by pstadler** [comment]
The solution is to collect the files you'd like to transfer with `find` or a similar command. There's currently no way to make `plan.transfer()` use a different method than `--from-file`. Please let me know if you have any further questions.
