### ISSUE TITLE
Can I run a flightplan via javascript?

### ISSUE THREAD

**Issue by reinzor** [pstadler/flightplan#74]
I see how I can use the cli to run a flightplan. Is it also possible to run plans via javascript (something like plan.run()) ?

Thanks

**Comment by pstadler** [comment]
Absolutely, try `plan.run(task, target, options)`

https://github.com/pstadler/flightplan/blob/master/lib/index.js#L312

**Comment by reinzor** [comment]
Thanks!

-Rein
