### ISSUE TITLE
transport.exec(), callback when new stdout available, is this possible?

### ISSUE THREAD

**Issue by reinzor** [pstadler/flightplan#77]
Hi,

I'm using transport.exec() to execute files on my remote. However, the result is displayed after the exec() has finished. Is it possible to provide a callback function that gets called when new stdout, stderr is available so that I can stream the console output?

Thanks,

Rein

**Comment by pstadler** [comment]
Unfortunately that's not possible at this moment. Can you further explain me what you want to solve by handling stdout/err as streams?

**Comment by reinzor** [comment]
I would like to run a script remotely that takes longer than 10 minutes to
run and stream the output to the client. I've managed to accomplish this
now with use of the simple-ssh package (
https://www.npmjs.com/package/simple-ssh) (with the -t option).

-Rein
