### ISSUE TITLE
List all available tasks

### ISSUE THREAD

**Issue by amsardesai** [pstadler/flightplan#80]
It would be great to be able to call `fly -T` and obtain a list of possible tasks. This could be similar to the `cap -T` for listing available recipes in capistrano. 

Capistrano gives an output that looks like this:

```bash
cap deploy               # Deploys your project.
cap deploy:check         # Test deployment dependencies.
cap deploy:cleanup       # Clean up old releases.
cap deploy:migrate       # Run the migrate rake task.
...
```

Flightplan's output could look similar. (sans descriptions since there's no way to specify them yet)

```bash
fly build:production
fly build:staging
fly deploy:production
fly deploy:staging
...
```

Thoughts?

**Comment by pstadler** [comment]
The question is whether tasks and targets should be listed separately. What do
you think?

```
Tasks:            Targets:
default           development
deploy            staging
reload            production
setup                
```
The count of functions to be executed / target hosts could be displayed as well:
```
Tasks:            Targets:
default (2)       development (1)
deploy  (5)       staging     (1)
reload  (1)       production  (?) # <-- using dynamic config
setup   (2)               
```

**Comment by amsardesai** [comment]
Sounds like a great idea to list them separately. Not sure if the count is needed though, I personally prefer the first one since the output is simple and easy to understand.

**Comment by pstadler** [comment]
:+1:

**Comment by zxqfox** [comment]
:+1: wow.

**Comment by grega** [comment]
This would be tremendously useful to have!

**Comment by sergeifilippov** [comment]
:+1:

**Comment by pstadler** [comment]
0.6.7 now supports the following commandline options:
```
-t, --targets            output available targets
-T, --tasks              output available tasks
```
It will also list available targets when the `target` argument is missing, i.e.

```
$ fly
Error: No target specified. Use `--help` for more information

Available targets:
  single
  multi
```
