### ISSUE TITLE
localhost ● failed (null)

### ISSUE THREAD

**Issue by samuelbeek** [pstadler/flightplan#85]
Whenever i do either fly production or fly staging, I get this weird error. Does anybody know how to fix this? It's hard to debug since it just says "null". 

    ✈ Running default:staging
    ✈ Executing local task
    localhost Copy files to remote hosts
    localhost $ git ls-files
    localhost ● failed (null)
    ● Command exited abnormally on localhost

Thanks in advance!

**Comment by pstadler** [comment]
Can you try something like `local.exec('echo foo')`? null is indeed a strange error. What OS are you on?

**Comment by samuelbeek** [comment]
This is the response. I'm on Yosemite and fly used to work before in this project. 

![schermafbeelding 2015-05-18 om 17 59 44](https://cloud.githubusercontent.com/assets/248098/7684607/b904dab0-fd87-11e4-9177-e49026ca8ced.png)

**Comment by lucasinteractive** [comment]
I can reproduce this issue with the following flightplan.js:

```javascript
var plan = require('flightplan');
plan.target('production', {});
plan.local(function(local) {
    var files = local.exec('find .', {silent: false}).stdout.split('\n');
});
```
``` 
$ fly production
[...]
localhost ● failed (null)
● Command exited abnormally on localhost
```

It interrupts between 13000 and 17000 files. But it breaks not on every run at the same file. 
``` 
$ fly production | wc -l
16640
$ fly production | wc -l
16017
$ fly production | wc -l
16552
```

**Comment by pstadler** [comment]
@samuelbeek, @lucasinteractive 

Try to increase the buffer size, e.g.

```javascript
local.exec('find .', {exec: {maxBuffer: 10000*1024}});
```

See: https://github.com/pstadler/flightplan#advanced-options

**Comment by lucasinteractive** [comment]
Yes now runs completely. So for me it's solved. Maybe it works with ```git ls-file``` the same way.
