### ISSUE TITLE
enable colors?

### ISSUE THREAD

**Issue by theoephraim** [pstadler/flightplan#86]
Im trying to run some remote commands to stream logs (specifically `pm2 logs`).

Any tips on how to enable colors to come through?

**Comment by pstadler** [comment]
Try `transport.exec('TERM=xterm-color pm2 logs');`. If this works you could also put `export TERM=xterm-color` to your bashrc (or the equivalent) used by your login shell.

Please let me know if this works for you.

**Comment by Iambecomeroot** [comment]
I tried this for `local.exec('gulp build')` and it didn't work. Tips?
