### ISSUE TITLE
Security Advisory: Semver ReDOS vulnerability

### ISSUE THREAD

**Issue by StevenLangbroek** [pstadler/flightplan#88]
Just noticed this in the badge: https://nodesecurity.io/advisories/semver_redos

> semver is vulnerable to regular expression denial of service (ReDoS) when extremely long version strings are parsed.

> Update to a version 4.3.2 or greater

Want me to open a PR?

**Comment by pstadler** [comment]
Yeah why not, please bump flightplan to the next minor version in package.json, will publish it then asap.

Thanks a lot
Patrick

**Comment by StevenLangbroek** [comment]
#89
