### ISSUE TITLE
How to pass --harmony to the fly command?

### ISSUE THREAD

**Issue by imrefazekas** [pstadler/flightplan#90]
I have ES6 codebase and ES6 Gulp files and even the code in the flightplan.js is ES6-based...

How can I specify the '--harmony' flag to flightplan?

**Comment by pstadler** [comment]
`fly --harmony ...` does the trick

**Comment by pstadler** [comment]
Please reopen this ticket if you have any further questions.

**Comment by imrefazekas** [comment]
fly --harmony ... does the trick ---- this definitely do not do anything ....

**Comment by imrefazekas** [comment]
first line of my flightplan file:

    var config = require('./configServices').env().argv().config();

That config services is using functions definitions like this:

    env: () => {
		_.merge( this.conf, process.env );
		return this;
	},

And flightplan dies here because of the ()=>
Running that line with simple node using --harmony work perfectly.

**Comment by imrefazekas** [comment]
fly --harmony staging
	✈ Running default:staging
	✈ Executing local task
	localhost Run build
	localhost $ gulp build
	localhost > /.../configServices.js:5
	localhost > 	env: () => {
	localhost > 	      ^
	localhost > SyntaxError: Unexpected token )
