### ISSUE TITLE
How to pass --harmony to the fly command?

### ISSUE THREAD

**Issue by imrefazekas** [pstadler/flightplan#91]
I have ES6 codebase and ES6 Gulp files and even the code in the flightplan.js is ES6-based...

fly --harmony ... does not resolve it  ....

first line of my flightplan file:

    var config = require('./configServices').env().argv().config();

That config services is using functions definitions like this:

    env: () => {
		_.merge( this.conf, process.env );
		return this;
	},

And flightplan dies here because of the ()=>
Running that line with simple node using --harmony work perfectly.

Flightplan result:

	fly --harmony staging
	✈ Running default:staging
	✈ Executing local task
	localhost Run build
	localhost $ gulp build
	localhost > /.../configServices.js:5
	localhost > 	env: () => {
	localhost > 	      ^
	localhost > SyntaxError: Unexpected token )

**Comment by pstadler** [comment]
Duplicate of #90.

For me it's working fine. I don't know what the problem on your side is.

**Comment by imrefazekas** [comment]
Tried to reopen my ticket but no such feature was available, I presume only you could have done it.

Me neither. Very simple file I'm using, latest flightplan and nodejs.

**Comment by pstadler** [comment]
Which node version do you have? `node --version`

**Comment by imrefazekas** [comment]
0.12.4

**Comment by imrefazekas** [comment]
Removed all node libs and the node itself and result was the same.
Strangely enough, an OS reinstall helped....
