### ISSUE TITLE
error in installing flightplan global

### ISSUE THREAD

**Issue by Robert-Janagap** [pstadler/flightplan#93]
hello this is my first time to install flightplan in my machine. I can't install it.

$ npm install -g flightplan
-

> fibers@1.0.5 install C:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\fl
ightplan\node_modules\fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
|
C:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\flightplan\node_modules\f
ibers>if not defined npm_config_node_gyp (node "c:\Users\Robert Yasay\AppData\Ro
aming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\nod
e-gyp.js" rebuild --release )  else (rebuild --release )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (c:\Users\Robert Yasay\AppData\Roaming\npm\no
de_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at c:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\npm
\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Users\\Robert Yasay\\AppData\\Roaming\\npm\\node_mo
dules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--release"
gyp ERR! cwd C:\Users\Robert Yasay\AppData\Roaming\npm\node_modules\flightplan\n
ode_modules\fibers
 ERR! node -v v0.12.3
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
Build failed
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\Robert Yasay\\Ap
pData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "flightp
lan"
npm ERR! node v0.12.3
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Robert Yasay\npm-debug.log

**Comment by pstadler** [comment]
Python is missing in your environment. Check this section: https://github.com/TooTallNate/node-gyp#installation

Please note that you don't have to install node-gyp itself, but only its dependencies (Python 2.7.3)
