### ISSUE TITLE
Add a call back in option to support process on interruption

### ISSUE THREAD

**Issue by Neil-Ni** [pstadler/flightplan#94]
Context:
- I recently added a remote `log` task to use `pm2 logs` on my server. This task works perfectly because I can stream my log on my local in one tab to monitor my deploy task.
- However, the usual way to stop `pm2 logs` is to do ctrl+c to end the process on the server
- Currently, if I do ctrl+c on my `fly log:production`, it will reply `Flightplan was interrupted` but the process on server is still running.

Possible solution/syntax:

```
var onInterrupt = function () {
  remote.exec('kill $(ps aux | grep ' pm2 logs ' | awk '{print $2}')');
}

plan.remote(['log'], function(remote) {
  remote.exec('pm2 logs', { onInterrupt : onInterrupt });
});
```

I'm happy to take this task and submit a PR later, but would like to have a discussion first and see if something similar has been done :)

**Comment by pstadler** [comment]
Try this, and let me know if it helps:
```javascript
$ remote.exec('pm2 logs', {exec: {pty: true}});
```

**Comment by pstadler** [comment]
There won't be a callback
