### ISSUE TITLE
Unexpected 'Command exited abnormally'

### ISSUE THREAD

**Issue by grega** [pstadler/flightplan#95]
I'm running a task which simply executes `sudo puppet agent -t` remotely. The command works fine when executed on the remote box via SSH:

```
user@host:~ sudo puppet agent -t
Info: Retrieving plugin
...
Notice: Finished catalog run in 80.47 seconds
user@host:~
```

When I run the command via a Flightplan task it also executes fine but then proceeds to report a failure:

```
fly puppet:staging
✈ Running puppet:staging
✈ Connecting to 'host'
✈ Executing remote task on host
host $ sudo puppet agent -t
host > Info: Retrieving plugin
...
host > Notice: Finished catalog run in 83.33 seconds
host × failed (2)
× Command exited abnormally on host
```

I can't figure out why it's failing as the command is running & exiting just fine.

**Comment by grega** [comment]
Got it; the Puppet command was exiting with a status code of 2, which Flightplan is identifying as an error (correctly, I believe). This is due to the `-t` flag being used which enables `--detailed-exitcodes; from the manpage:

"If this is enabled, an exit code of '2' means there were changes, an exit code of '4' means there were failures during the transaction, and an exit code of '6' means there were both changes and failures"

Hopefully this might help someone in the future.

**Comment by pstadler** [comment]
Glad you could solve the problem. Please note that you can also run commands
with non-zero exit codes and capture them:

```javascript
var result = remote.sudo('puppet agent -t', { failsafe: true });

switch (result.code) {
  case 2:
    remote.log('puppet agent: changes');
    break;
  
  case 4:
    remote.log('puppet agent: failures');
    break;
  
  case 6:
    remote.log('puppet agent: changes and failures');
    break;
}
```

**Comment by grega** [comment]
Good to know! (thanks for all your work on Flightplan).
