### ISSUE TITLE
forever and flightplan

### ISSUE THREAD

**Issue by NikonMcFly** [pstadler/flightplan#98]
everything seems to be fine up to the last piece of code i have...i have tried everything but i still dont understand about /usr/bin/env...is it my computer or the server im pushing it too. I really dont know at this point. 

● ok
 $ forever stop ~/court/server.js
> /usr/bin/env: node: No such file or directory
 ● safely failed (127)
$ forever start ~/court/server.js
 > /usr/bin/env: node: No such file or directory
× failed (127)
× Command exited abnormally on *IP*

**Comment by NikonMcFly** [comment]
I found out where the issue is coming from and it is the .bin file but I still do not understand why that wont work

**Comment by pstadler** [comment]
Make sure that the node binary is in your `$PATH` when executing `forever` on either your local or remote host. This may helps: http://stackoverflow.com/questions/30281057/node-forever-usr-bin-env-node-no-such-file-or-director

**Comment by NikonMcFly** [comment]
Awww Thank you! that works
